name: Benchmark Test

on: [push, pull_request]

jobs:
  test:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Benchci
        run: curl -sfL https://raw.githubusercontent.com/wenqiq/benchci/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run Benchmark
        run: benchci -config test/performance/benchmark.yml
